# This is a basic workflow to help you get started with Actions

name: Fork Sync

# Runs at 13:00 UTC every day
on:
  schedule:
    - cron: '0 13 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: TG908/fork-sync@v1.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        owner: 'speckleworks'
    - uses: actions/checkout@v2
    - run: |
        git remote add upstream https://github.com/speckleworks/SpeckleAdmin.git
        git fetch upstream
        git remote set-url origin https://jenessaman:${{ secrets.GITHUB_TOKEN }}@github.com/arup-group/SpeckleAdmin.git
        git push origin --tags
